spring.datasource.url: jdbc:mysql://127.0.0.1:3306/Project
spring.datasource.username: root
spring.datasource.password: Rome2totalwar
spring.datasource.driverClassName: com.mysql.cj.jdbc.Driver
spring:
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create
server.port: 6500
---
environment: test
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password: test
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
  h2:
    console:
      enable: true

